### ISSUE TITLE
Unable to use the new Color Preference

### ISSUE THREAD

**Issue by JoseGD** [consp1racy/android-support-preference#25]
Hi, I couldn't get the new Color preference working.

After including in my gradle file the `compile 'net.xpece.android:support-preference-color:0.6.0'` line, I get

> Error:Failed to resolve: xpece-android-support-preference:support-preference:unspecified

**Comment by consp1racy** [comment]
For now try 

```
compile 'net.xpece.android:support-preference-color:0.6.0@aar'
compile 'net.xpece.android:support-preference:0.6.2'
```

Let me know if it still doesn't work. This will be fixed in 0.6.3 patch release.

**Comment by JoseGD** [comment]
The 1st line, ending with @aar, works. The 2nd causes the build to fail

**Comment by consp1racy** [comment]
Sorry, typo.

**Comment by consp1racy** [comment]
Version 0.7.0 should cause no issues in this regard.

**Comment by JoseGD** [comment]
Sorry to tell you that it is causing issues at least in my project:
`compile 'net.xpece.android:support-preference-color:0.7.0@aar'` compiles.
`compile 'net.xpece.android:support-preference-color:0.7.0'`doesn't compile.

**Comment by consp1racy** [comment]
Goddammit! Any error message?

**Comment by consp1racy** [comment]
Fixed for people who haven't touched it yet. Shouldn't be an issue in next releases, unless I forget it.

**Comment by JoseGD** [comment]
Still fails for me. Error message:

> Error:Failed to resolve: xpece-android-support-preference:support-preference:[0.7.0,0.8.0)

Adding the @aar sufix solves the issue.

I don't know if this have something to do, but I have upgraded to Android Studio 2 yesterday, and to make sure I have the latest support library (I've seen the comment `// depends on preference-v7 r23.3.0` in readme) I kept "Android Support Repository, rev 30" and removed "Android Support Library 23.2.1" in SDK Manager.

I've done this after asking asking in G+ (https://plus.google.com/+AndroidDevelopers/posts/iTDmFiGrVne) why I couldn't see the 23.3.0 release in SDK Manager. The docs say "Note: If you're developing with Android Studio, select and install the Android Support Repository item instead".

**Comment by consp1racy** [comment]
The issue is I currently have to manually fix the dependency from

```
xpece-android-support-preference:support-preference:unspecified
```

to

```
net.xpece.android:support-preference:[0.7.0,0.8.0)
```

when releasing the library.

The first time (0.6.0) i didn't know at all. The second time (0.7.0) I fixed only the version and didn't notice the groupId being wrong.

I uploaded fixed .pom file (maven metadata) but there's a million caches on the way to your Android Studio so you probably won't pick it up. **For now you're stuck with @aar suffix and manually importing `net.xpece.android:support-preference` as well.**

Thank you for letting me know and let's pray I get it right in next release.
