### ISSUE TITLE
SortCursor crash - java.lang.IllegalArgumentException: column 'title_key' does not exist

### ISSUE THREAD

**Issue by dirkam** [consp1racy/android-support-preference#62]
I can see the following crash reported by Crashlytics.
```java
Fatal Exception: java.lang.IllegalArgumentException: column 'title_key' does not exist
       at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:333)
       at net.xpece.android.support.preference.SortCursor.(SortCursor.java:74)
       at net.xpece.android.support.preference.RingtoneManagerCompat.getCursor(RingtoneManagerCompat.java:121)
       at net.xpece.android.support.preference.XpRingtonePreferenceDialogFragment.onCreate(XpRingtonePreferenceDialogFragment.java:162)
       at android.support.v4.app.Fragment.performCreate(Fragment.java:2068)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1055)
       at android.support.v4.app.BackStackRecord.setLastIn(BackStackRecord.java:838)
       at android.support.v4.app.BackStackRecord.calculateFragments(BackStackRecord.java:861)
       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:719)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1677)
       at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:536)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7224)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```
Affected devices:
```
Galaxy J5 30%
Galaxy J3(2016) 19%
Galaxy S7 6%
Galaxy Note 53%
Galaxy J 73%
```
Affected OS versions:
```
5 67%
6 33%
```
It happens rarely and apparently this issue is present since `1.0.2` though I don't have too much data on newer versions than `1.0.3`
Couldn't reproduce this on my end.

**Comment by consp1racy** [comment]
All Samsung, heh.

There's no reason for crash. So if it crashes I'll let it fall back to system handler, that is the `new Intent(ACTION_RINGTONE_PICKER)`. You'll lose the theming abilities but at least it will work instead of crashing.

**Comment by dirkam** [comment]
Yep, that seems to be the only workaround. Thanks.

**Comment by consp1racy** [comment]
Fixed in 1.2.6.

**Comment by dirkam** [comment]
Crashes still happen in SortCursor, but apparently with a different stack trace
```java
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.compareToIgnoreCase(java.lang.String)' on a null object reference
       at net.xpece.android.support.preference.SortCursor.(SortCursor.java:82)
       at net.xpece.android.support.preference.RingtoneManagerCompat.getCursor(RingtoneManagerCompat.java:121)
       at net.xpece.android.support.preference.XpRingtonePreferenceDialogFragment.onCreate(XpRingtonePreferenceDialogFragment.java:164)
       at android.support.v4.app.Fragment.performCreate(Fragment.java:2246)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1377)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
       at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
       at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
       at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
       at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5912)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
```

Would you please check this? Thank you!

**Comment by consp1racy** [comment]
Please open another issue for this, in the meantime I'll look into it. Also post what devices does this happen on. Thanks.
